services:
  postgres:
    image: postgres:18
    container_name: books-postgres
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql

volumes:
  postgresql: