spring.application.name=tree
server.port=${PORT:8081}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/trees}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.jooq.sql-dialect=POSTGRES
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.accept-float-as-int=false
spring.jackson.mapper.allow-coercion-of-scalars=false
spring.datasource.hikari.maximum-pool-size=${MAX_DATASOURCE_POOL_SIZE:20}
spring.threads.virtual.enabled=true
#spring.web.error.include-message=always